version: '3.1'

services:
  tronscan:
    image: tronscan/api:latest
    ports:
      - "9000:9000"
    environment:
      NODE_FULL_IP: "https://api.trongrid.io"
      NODE_FULL_PORT: "80"
      NODE_SOLIDITY_IP: "https://api.trongrid.io"
      NODE_SOLIDITY_PORT: "80"
      ENABLE_SYNC: "true"
      ENABLE_NETWORK_SCANNER: "true"
      SECRET_KEY: "aSLtAkzrIY9pTPyboOih"
  redis:
    image: redis:4.0
  pgsql:
    image: tronscan/db:latest
